keys:
  users: &age_keys
    - &wallago_squid age1rr4gyh2dmpaplgcxswm4xt4t449z2tcyc8a7q0ql8we6vzkevpvsd6fzce
  yubikey: &pgp_keys
    - &yubikey_001 7E60EC8F165F780F
creation_rules:
  - path_regex: nixos/common/secrets.ya?ml$
    key_groups:
      - age:
          - *wallago_squid
        pgp:
          - *yubikey_001
