keys:
  users: &age_keys
    - &wallago_squid age1dzwegqyge33deld53k5cvc0gnwulp9xl3nhqdd7a9y8zcjaq7aqqrr67mn
  yubikey: &pgp_keys
    - &yubikey_001 7E60EC8F165F780F
creation_rules:
  - path_regex: nixos/common/secrets.ya?ml$
    key_groups:
      - age:
          - *wallago_squid
        pgp:
          - *yubikey_001
